### ISSUE TITLE
Moving source to src/ folder and bin to bin/ folder

### ISSUE THREAD

**Issue by fraga** [DrWhax/truecrypt-archive#16]
Maybe it's only me, but when I'm browsing truecrypt-archive repo, there's some scroll down work until we reach the documentation.

What do you think if we move source files into src/ folder and then bin files into a bin folder (or maybe build/ folder)?

I think the repo would be more readable. Another alternative is the wiki.

**Comment by stefansundin** [comment]
Personally I think this is perfectly fine. Everything is on one page. It's not overwhelming. And you can simply click or link to README.md, which is on the top.

I used the wiki before for the doc/ dir, but moved away from it since it makes it more difficult to clone and PR. So I don't want to go back to that.

**Comment by fraga** [comment]
Understand @stefansundin :)

Will close the issue tks for your input
